### ISSUE TITLE
Response / parameter search confusing

### ISSUE THREAD

**Issue by oysteoh** [equinor/webviz-ert#235]
There is a `search` bar available which works as expected, but users ( test-users never seen this before ) attempts to write in the drop-down selection box underneath where the selected responses / parameters goes. We should disable the box from input ( and why is it indicated as a dropdown? It seems to just get filled with selected keys? 
![Skjermbilde 2022-03-29 kl  12 03 41](https://user-images.githubusercontent.com/4184190/160588113-87c53731-4bb5-474f-b26f-48041db98979.png)
)

**Comment by DanSava** [comment]
This is a drawback of dash not having a supported selection list and having us implement "nice to have functionality". 

> We should disable the box from input 

By box you mean the dropdown box I assume. 

> why is it indicated as a dropdown?

That is because it is a dropdown 

> It seems to just get filled with selected keys?

I think that is like that because it seems the most natural way to keep track of the user selections. I cannot think at the moment of a better way to keep track of the selections with the limited set of dash default components. There might be some other options in webviz core components that will fulfil our need, but I am not aware of them at the moment.

**Comment by oysteoh** [comment]
> By box you mean the dropdown box I assume. I agree it would be best if it is just possible to disable text input for the selected dropbox

yes, meaning the dropdown- the user tried to search from that box and nothing happened other than a message stating `No results found`

**Comment by oysteoh** [comment]
> I think that is like that because it seems the most natural way to keep track of the user selections. I cannot think at the moment of a better way to keep track of the selections with the limited set of dash default components. There might be some other options in webviz core components that will fulfil our need, but I am not aware of them at the moment.

I think it is fine as-is as long as we disable input from users and maybe highlight the search-box or get it to stand out a bit more? 🤔
