### ISSUE TITLE
Response correlation viewer - Tornado plot ordering

### ISSUE THREAD

**Issue by oysteoh** [equinor/webviz-ert#304]
Heatmap and tornado plot automatically order by weak -> strong correlation and makes it hard to keep track of what is going on when clicking around. Should be possible to toggle on/off this ordering. Pop-up box showing info when hover the heatmap gets in the way. ~~Add column names.~~
![feedback6](https://user-images.githubusercontent.com/4184190/174232961-7f55213e-0299-4547-b63d-c429b188f2be.png)

**Comment by hnformentin** [comment]
Regarding:
- "Pop-up box showing info when hover the heatmap gets in the way.", the info expected to appear on hovering are only response, parameter and correlation value?
- The column names in the heatmap are the name of the parameters, correct?
- Should we also aim to display the correlation value when hovering the tornado plot?

**Comment by frode-aarstad** [comment]
Created a seperate issue for column names #318

**Comment by valentin-krasontovitsch** [comment]
@hnformentin did you ever get a response to your first or third question?

**Comment by hnformentin** [comment]
No, second point seems to be solved, so maybe starting with the first one is safe. We know we want some information when hovering over the heatmap, if it is not response, parameter and correlation value, the request should not be far from that!

**Comment by valentin-krasontovitsch** [comment]
after a chat we agreed the information one probably wants to see is already displayed in the hover text, probably.
this should be about making sure that the hover text doesn't cover up too much of the heatmap.
one possible solution, moving the text elsewhere, seems rather difficult to realize - the dash / plotly interface doesn't seem to offer that option, nor does it seem to be possible to move the tooltip (part of an svg) using just css. disabling the tooltip and recreating it in our own element, where we can freely choose the placement, requires javascript level hacking into the events triggering the tooltip / hover, which is as far as i can tell impossible from dash / plotly.

finally, the approach must be changing the content and / or formatting thereof, to change the size of the hover element. i'm thinking font size, shortening the displayed information, and removing for instance the ensemble id (shown when multiple ensembles are seleceted; displayed at the moment as just `trace [i]`). another option is to create a UI element that for controls for instance the font size, or toggles the hover info, or ...

this seems very open at the moment, at least for me. i think i might create a new issue to address the hovertext problem, as perhaps more input is necessary, which i probably cannot get right now due to vacation times, and just focus on the sorting part
