### ISSUE TITLE
Nightly tests fail to download chromium-driver

### ISSUE THREAD

**Issue by berland** [equinor/webviz-ert#453]
**Describe the bug**
```
+ echo 'Downloading chromedriver v120.0.6099.129 for chromium-browser v120.0.6099.129'
+ wget -O chromedriver.zip https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/120.0.6099.129/linux64/chromedriver-linux64.zip
Downloading chromedriver v120.0.6099.129 for chromium-browser v120.0.6099.129
--2024-01-08 12:37:39--  https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/120.0.6099.129/linux64/chromedriver-linux64.zip
Resolving edgedl.me.gvt1.com (edgedl.me.gvt1.com)... 34.104.35.123, 2600:1900:4110:86f::
Connecting to edgedl.me.gvt1.com (edgedl.me.gvt1.com)|34.104.35.123|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-01-08 12:37:39 ERROR 404: Not Found.
```

https://github.com/equinor/komodo-releases/actions/runs/7446571248/job/20257957472

**Expected behavior**
No problemo.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by berland** [comment]
The chromium version apparently varies between our runners:

```
[havb@st-linapp1192:~]$ chromium-browser --version
Chromium 119.0.6045.159 Fedora Project
```

```
[havb@s034-lcatop01:~]$ chromium-browser --version
Chromium 120.0.6099.109 Fedora Project
```

**Comment by kwinkunks** [comment]
This happened once before -- see https://equinor.slack.com/archives/C02GLHN886R/p1699533785059899?thread_ts=1699431460.088439&cid=C02GLHN886R -- and the problem seems to be that we are sometimes getting unsupported versions of Chromium on the runners. They change every week or two. When they are unsupported -- for whatever reason -- there is no chromedriver for them so the link 404's. AFAICT, there is no way around it, since these unsupported versions simply do not have a driver to download.

I did not test if Selenium can use a driver that is 'close'.

Other things I can think of:

- Figure out what process is making these unsupported updates (I assume it's something from Redhat)
- Install Chrome ourselves (is this even possible?), or use another browser that we can control, eg Firefox
-

**Comment by kwinkunks** [comment]
I guess this issue can be combined with https://github.com/equinor/webviz-ert/issues/446 (in which I assumed that this flakiness would be rare)

**Comment by kwinkunks** [comment]
OK, I see how to fix this -- we can hit https://googlechromelabs.github.io/chrome-for-testing/latest-patch-versions-per-build.json and get the last known good version from there

**Comment by eivindjahren** [comment]
Seems like this didn't work. Should we reopen?
