### ISSUE TITLE
Display gen data names instead of general observation names

### ISSUE THREAD

**Issue by oysteoh** [equinor/webviz-ert#82]

**Comment by oysteoh** [comment]
should be clarified with eivind exactly what he meant

**Comment by eivindsm** [comment]
Some prosa to increase the understanding of the issue: 
When conditioning to a datatype which is not natively supported (ecl summary vectors, basically) the user is left with the option of defining his own data type and point ERT to a file from which simulated results can be extracted. The most typical example is RFT (reservoir formation pressure) eg pressure readings along a wellbore obtained while drilling.

In the config file this may look like this:
  --        ert id            input format         report step     Result file name
GEN_DATA  ROP_4_SIM         INPUT_FORMAT:ASCII   REPORT_STEPS:1  RESULT_FILE:RFT_ROP_4_%d
GEN_DATA  ROP_5_SIM         INPUT_FORMAT:ASCII   REPORT_STEPS:1  RESULT_FILE:RFT_ROP_5_%d
GEN_DATA  RWI_2_SIM         INPUT_FORMAT:ASCII   REPORT_STEPS:1  RESULT_FILE:RFT_RWI_2_%d
GEN_DATA  RWI_3_SIM         INPUT_FORMAT:ASCII   REPORT_STEPS:1  RESULT_FILE:RFT_RWI_3_%d

In the observation file:
-- RFT data

GENERAL_OBSERVATION     RWI_2_OBS     {   DATA=  RWI_2_SIM  ;  RESTART=1; OBS_FILE= ./rft/RWI_2.obs  ; };
GENERAL_OBSERVATION     ROP_5_OBS     {   DATA=  ROP_5_SIM  ;  RESTART=1; OBS_FILE= ./rft/ROP_5.obs  ; };
GENERAL_OBSERVATION     RWI_3_OBS     {   DATA=  RWI_3_SIM  ;  RESTART=1; OBS_FILE= ./rft/RWI_3.obs  ; };
GENERAL_OBSERVATION     ROP_4_OBS     {   DATA=  ROP_4_SIM  ;  RESTART=1; OBS_FILE= ./rft/ROP_4.obs  ; };

When plotting  the observations and the simulated data are combined. This issue is concerning which labels to display, ie the GEN_DATA names or the GENERAL_OBSERVATION names. I am inclined towards using the GEN_DATA as they are closer associated with the simulation runs (and this is what the qt-plotter is doing).
