### ISSUE TITLE
 Authentication issue on webviz

### ISSUE THREAD

**Issue by oysteoh** [equinor/webviz-ert#87]
Currently the users getting logged out after a while, and it is not optimal how webviz does authentication. We should poke webviz team and make sure this is getting solved in a proper way by them or making an agreement that we will fix it.

**Comment by dotfloat** [comment]
Could you elaborate?

**Comment by oysteoh** [comment]
This needs to be discussed with the webviz team and followed up with them. They should have initiated a discussion with security people regarding what to do

**Comment by dotfloat** [comment]
@asnyv : We discussed this before vacation. One of the problems was that webviz uses HTTPS and installs an SSL cert for you. This doesn't work out of the box on Ubuntu / macOS (missing dependencies). I've additionally not had any success trying to use Firefox. Webviz refuses to run without creating a cert, but I still get the scary SSL page from Firefox, making everything pointless.

In our discussion, Anders said that his concern was that users are conditioned to look for the lock icon left of the address bar signifying a secure connection, and that this doesn't exist when using plain HTTP. While HTTP with authentication tokens is entirely secure within Equinor, the user doesn't get confirmation from their browser. He said he'd ask IT security about what to do in that case. Did anything come out of it?

**Comment by anders-kiaer** [comment]
I did a new visual test in Firefox and Chromium (last one was two years ago), and I would say we also from a pedagogical point of view today can safely remove https _localhost_. Here are my results in recent versions of the two:

**Firefox address bar for external http (non-localhost):**
![firefox_external_http](https://user-images.githubusercontent.com/31612826/103764759-5a58af80-501c-11eb-9073-70481467f890.png)
**Chromium address bar for external http (non-localhost):**
![chromium_external_http](https://user-images.githubusercontent.com/31612826/103764760-5a58af80-501c-11eb-89bc-323acc1d4d61.png)
**Firefox address bar for localhost http:**
![firefox_localhost](https://user-images.githubusercontent.com/31612826/103764761-5a58af80-501c-11eb-8f9f-1f72bcbf65e3.png)
**Chromium address bar for localhost http:**
![chromium_localhost](https://user-images.githubusercontent.com/31612826/103764763-5af14600-501c-11eb-8be0-940c427568cc.png)
**Chromium address bar for localhost http if clicking on the icon:**
![chromium_localhost_hidden](https://user-images.githubusercontent.com/31612826/103764939-ac013a00-501c-11eb-97d5-ff530435222d.png)

I.e. it is only when clicking on the information logo in Chromium the "Your connection is not secure" appears with recent browser versions. In Firefox even clicking on the logo does not show this for localhost :+1: (they split visual behavior even more between localhost and non-localhost).

I would therefore now vote for simply :hocho: away the HTTPS/SSL code in `webviz-config` - at the same time we make it quite a lot simpler to start using Webviz on different OSes and setups (and `webviz-config` obviously gets less code to maintain).

When the code removal in https://github.com/equinor/webviz-config/issues/290 is done, https://github.com/equinor/webviz-config/issues/332 should maybe also be considered (e.g. in some "deprecation period" instruct browser through appropriate header to not use HTTPS on webviz localhost, such that users are not redirected to non-existing https due to "browser memory").

**Comment by oysteoh** [comment]
That sounds good @anders-kiaer ! Would your team prioritize this issue in near future - as it will make our lives easier pushing the test of the visualization in ERT to more people.

**Comment by asnyv** [comment]
@oysteoh that might be possible. Near future is of course a very relative term... I have to ask though: If you have the resources and are willing to look into the issues yourselves, we are very open for contributions to `webviz-config` 😉 We have a lot on the backlog...

Not sure if the challenges in [equinor/webviz-config#332](https://github.com/equinor/webviz-config/issues/332) makes it necessary to do the two issues in order with some period in between, to avoid that Chrome existing webviz users are redirected to https anyways? Haven't looked into these issues before myself.

**Comment by oysteoh** [comment]
@asnyv we can put this into our priorities now and will have a go at it! If it is not to complicated / time consuming we will fix.

**Comment by asnyv** [comment]
That would be perfect @oysteoh 🤩 Thanks a lot! 
If you need input let me know and we'll try to help 😊
